[package]
name = "cmv"
version = "0.1.0"
edition = "2021"

[dependencies]
fxhash = "0.2"
rand = "0.8"

[dev-dependencies]
criterion = "0.5"
rand_chacha = "0.3.1"

[[bench]]
name = "bench"
harness = false
